language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  api_key:
    develop:
      secure: dOc9vnF5RicKFyZBGRSvZz+HovVZzpVijV0dCznMO2zpG9jNm3jqSZ/6om1foreORS/AlNY/F2NZQBkYnn4QvOIhLjXY0ya9dVQJ4jelCfgxge2HidtWS8RgKFl+yc8Zo97Hokxqzh1hw/cvK4qbAw6Y6jO8kZaoH9XQY0Y3gPjnendCIXVwLshzBjUepjpiZEKuu5j5D0iOxjTb4Kvzl+Hhsq9LEhmG/H5Co/ZI0BkiAZR81YIQTA86kuWhXw2Q88C8Y4TwHPUQ6uflxqzVyUBXii4g14P0WQfEZwgeScS8Jtf5tTomeDalC74RxMMGM/tNP9pXgZVq4irldjQpx4xxdSYbq+pqDkS6oXMk6kdSYn5IMBB909oJPav+sF3dr0+Z5yh8dMLQDXWb3zujolTYC/vgnFRPHygpH7ur16KqI8k1zv3JIUMyQ3Q7wLg8oRU02zitBs6qVKx/NQOXJrtVFmp0KTb465r0ky8OWYXNn2SdVxLlssCLlNifSwg3NkfCVAxl+xaByBZGiEXz8ghLodMAg8/nYEEjbWqsbDxZWgdi/7h/DlqyBiZ+Wb4fyj5khpFB5Mls8Cv8NuOW1v3GnMNSbOZ+heffj41B6uADBu60e3vl1neoTSUMe/z3EZKUzJpCO+uYKl49jYiKJ6nAsAQVXEgg7c7lQ2LA5KQ=
    test:
      secure: Or3epN0DcsEqkZ/itErCOhnXB517T8+ZWJ5n67OeoTBrjKk8PVw2gRtzCA6dO4p/jT5JYaWEhfmZxyu6GtyFvPb9BAfF1SYjyc8aprQcMZ0Efcx2eNZYOXgDSPgilUn829KO/oErSgWLy9YzCIGhazEFG4gN8x/MytWceLbiJfJh6KUvlEQQli23l/80hjJg8X87XofJayxKmcgLI+G9HOkY7QPyN012E1S92I6213xb2s5KVPd9MPsEPU3FkHMGzOSd7ycBIFqRwYPSs0aN+4b68wxUO5M95aH4/0kT2HI0v6RTvcS2esblNLloAewRmGNyQU42CWB6hDtQ8nIhZhDoK/HGble9LVmTmpkGpi0oJXHmr2pqrd8zZQJDdFeGCRAHcbWpqGd6ZCIe2adkyAKM5eFzIH5ki+v6oz56ODuJ9u4NwTwNMBkdCjXAjN+XdnmUvQRUnTK0Aj6iagM1fYlC3eHT9w9NRPPmle0Ipd9sIV227n1FbW8VodxKXzWSG9DlUgx+uyVtGc+TCLqB9OxMpS258uh0DSqxik+K7eXV8c8H/pyjGQU/UMDIlPporITvfb2S4fzDdYuI9+Cf2WzrULB3u31cwQeJp6l6p1pevvOknJdhAL0CBlFhbH29U6Y6iOKCE4+jG+BbLY6qwe8hv88OeWima2ZtoL7gCt8=
  app:
    develop: vast-taiga-41047
    test: limitless-savannah-94199
