version: '2'
services:

  node-external-apvs:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    volumes:
      - "./gulpfile.js:/usr/src/app/gulpfile.js"
      - "./nodemon.json:/usr/src/app/nodemon.json"
      - "./app:/usr/src/app/app"
      - "./cache_node_modules:/usr/src/app/node_modules"
      - "./logs:/usr/src/app/logs"
    ports:
      - "3000:3000"
    environment:
    - LOGGING_PATH=/usr/src/app/logs/external-web.log
