version: '3'
services:
  help-with-prison-visits-external:
    build:
      context: .
    volumes:
      - "./app:/usr/src/app/app"
      - "./logs:/usr/src/app/logs"
      - "./uploads:/usr/src/app/uploads"
    networks:
      - hmpps_int
    depends_on:
      - clamav
    ports:
      - "3000:3000"
    env_file: ./.env

  clamav:
    image: quay.io/hmpps/hmpps-clamav:latest
    restart: always
    container_name: clamav-int
    networks:
      - hmpps_int
    ports:
      - "3310:3310"

networks:
  hmpps_int:
