version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@dev:alpha

# executors:
#   integration-tests:
#     docker:
#       - image: cimg/node:12.22-browsers
#       - image: circleci/redis:buster
#     working_directory: ~/app

parameters:
  alerts-slack-channel:
    type: string
    default: "help-with-prison-visits-alerts"

jobs:
  unit_test:
    executor:
      name: hmpps/node
      tag: 12.22-browsers
    steps:
      - checkout
      - run:
          name: Switch python
          command: sudo apt-get update -y && sudo apt-get install -y --no-install-recommends python-is-python3
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run Unit Tests
          command: npm run test
  # integration_test:
  #   executor: integration-tests
  #   steps:
  #     - checkout
  #     - attach_workspace:
  #         at: ~/app
  #     - run:
  #         name: Install missing OS dependency
  #         command: sudo apt-get install libxss1
  #     - run:
  #         name: Get wiremock
  #         command: curl -o wiremock.jar https://repo1.maven.org/maven2/com/github/tomakehurst/wiremock-standalone/2.27.1/wiremock-standalone-2.27.1.jar
  #     - run:
  #         name: Run wiremock
  #         command: java -jar wiremock.jar --port 9091
  #         background: true
  #     - run:
  #         name: Run the node app.
  #         command: npm run start-feature
  #         background: true
  #     - run:
  #         name: Wait for node app to start
  #         command: sleep 5
  #     - restore_cache:
  #         key: dependency-cache-{{ checksum "package-lock.json" }}
  #     - run:
  #         name: integration tests
  #         command: npm run int-test
  #     - store_test_results:
  #         path: test_results
  #     - store_artifacts:
  #         path: integration-tests/videos
  #     - store_artifacts:
  #         path: integration-tests/screenshots

workflows:
  version: 2
  security:
    jobs:
      - hmpps/veracode_pipeline_scan:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - veracode-credentials
            - hmpps-common-vars

